apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Gitea - Self-hosted Git server
resources:
- namespace.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- gitea-pvc.yaml
- gitea-deployment.yaml
- gitea-service.yaml
- ingress.yaml
