apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: homelab-app
    releaseName: monarch-api
    namespace: apps
    valuesFile: values.yaml
    includeCRDs: true
    # Use local chart path relative to this directory
    repo: file://../../../helm/homelab-app
