apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: namespace is created by cluster/core/monitoring (sync-wave 1)
resources:
  - prometheus-config.yaml
  - prometheus-rbac.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml
