apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: hajimari
    repo: https://hajimari.io
    version: 2.0.2
    releaseName: hajimari
    namespace: apps
    valuesFile: values.yaml
