{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homelab-app.fullname" . }}-data
  labels:
    {{- include "homelab-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if and .Values.postgres.enabled .Values.postgres.sidecar.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homelab-app.fullname" . }}-postgres
  labels:
    {{- include "homelab-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.sidecar.storageClass }}
  storageClassName: {{ .Values.postgres.sidecar.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.sidecar.storage }}
{{- end }}
---
{{- if and .Values.redis.enabled .Values.redis.sidecar.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homelab-app.fullname" . }}-redis
  labels:
    {{- include "homelab-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.sidecar.storageClass }}
  storageClassName: {{ .Values.redis.sidecar.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.sidecar.storage }}
{{- end }}
